__BASE__: [
  '../coco.yaml',
  './hyp.scratch.n.yaml',
  './yolov11-base.yaml'
]

network:
  depth_multiple: 0.50  # scales module repeats
  width_multiple: 0.25  # scales convolution channels
  max_channels: 1024
  scale: n
