__BASE__: [
  '../coco.yaml',
  './hyp.scratch.n.yaml',
  './yolov12-base.yaml',
]

overflow_still_update: False
network:
  scale: n
  depth_multiple: 0.50  # model depth multiple
  width_multiple: 0.25  # layer channel multiple
  max_channels: 1024