epochs: 600 # total train epochs
per_batch_size: 32  # 32 * 8 = 256
img_size: 640
conf_free: True
iou_thres: 0.7
ms_loss_scaler: dynamic
ms_loss_scaler_value: 65536.0
clip_grad: True
anchor_base: False
opencv_threads_num: 0  # opencv: disable threading optimizations

network:
  model_name: yolov12
  nc: 80  # number of classes
  reg_max: 16

  stride: [8, 16, 32]

  # YOLOv12n backbone
  backbone:
    # [from, repeats, module, args]
    - [-1, 1, ConvNormAct, [64, 3, 2]]     # 0-P1/2
    - [-1, 1, ConvNormAct, [128, 3, 2]]    # 1-P2/4
    - [-1, 2, C3k2, [256, False, 0.25]]
    - [-1, 1, ConvNormAct, [256, 3, 2]]    # 3-P3/8
    - [-1, 2, C3k2, [512, False, 0.25]]
    - [-1, 1, ConvNormAct, [512, 3, 2]]    # 5-P4/16
    - [-1, 4, A2C2f, [512, True, 4]]
    - [-1, 1, ConvNormAct, [1024, 3, 2]]   # 7-P5/32
    - [-1, 4, A2C2f, [1024, True, 1]]

  # YOLOv12n head
  head:
    - [-1, 1, Upsample, [None, 2, 'nearest']]
    - [[-1, 6], 1, Concat, [1]]            # cat backbone P4
    - [-1, 2, A2C2f, [512, False, -1]]     # 11

    - [-1, 1, Upsample, [None, 2, 'nearest']]
    - [[-1, 4], 1, Concat, [1] ]           # cat backbone P3
    - [-1, 2, A2C2f, [256, False, -1]]     # 14

    - [-1, 1, ConvNormAct, [256, 3, 2]]
    - [[ -1, 11], 1, Concat, [1]]          # cat head P4
    - [-1, 2, A2C2f, [512, False, -1]]     # 17

    - [-1, 1, ConvNormAct, [512, 3, 2]]
    - [[-1, 8], 1, Concat, [1]]            # cat head P5
    - [-1, 2, C3k2, [1024, True]]          # 20 (P5/32-large)

    - [[14, 17, 20], 1, YOLOv12Head, [nc, reg_max, stride]]  # Detect(P3, P4, P5)
