__BASE__: [
  '../coco.yaml',
  './hyp.scratch.m.yaml',
  './yolov12-base.yaml',
]

overflow_still_update: False
network:
  scale: m
  depth_multiple: 0.50  # model depth multiple
  width_multiple: 1.00  # layer channel multiple
  max_channels: 512
