__BASE__: [
  '../coco.yaml',
  './hyp.scratch.x.yaml',
  './yolov12-base.yaml',
]

overflow_still_update: False
network:
  scale: x
  depth_multiple: 1.00  # model depth multiple
  width_multiple: 1.50  # layer channel multiple
  max_channels: 512
