__BASE__: [
  '../coco.yaml',
  './hyp.scratch.med.yaml',
  './yolov8-base.yaml'
]

overflow_still_update: False
network:
  depth_multiple: 0.67  # scales module repeats
  width_multiple: 0.75  # scales convolution channels
  max_channels: 768
