# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  ut-test:
    strategy:
      matrix:
        os: [ubuntu-latest] # , macos-latest, windows-latest
        python: [3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/cpu_requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint mindyolo --rcfile=.github/pylint.conf
    - name: Test with unit test (UT) pytest
      run: |
        pytest tests/ut/
    - name: Test with system test (ST) pytest
      run: |
        pytest tests/st/